name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # تشغيل البناء داخل حاوية دكر الرسمية الخاصة بـ Kivy
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK inside Docker
        run: |
          buildozer -s android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rp2350-touch-app
          path: bin/*.apk
